version: '3'

services:
    postgres:
        image: postgres:10.3-alpine
        ports: 
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
